import { DockAppDef } from './dock-app.model';

export const DOCK_APPS: DockAppDef[] = [
  { id: 'notes', labelKey: 'dockNotes', icon: 'notes', pinnedMobile: true, tooltip: 'aboutMe' },
  {
    id: 'vscode',
    labelKey: 'dockVscode',
    icon: 'vscode',
    pinnedMobile: true,
    tooltip: 'codeProjects',
  },
  {
    id: 'photoshop',
    labelKey: 'dockPhotos',
    icon: 'photoshop',
    pinnedMobile: false,
    tooltip: 'photos',
  },
  { id: 'figma', labelKey: 'dockFigma', icon: 'figma', pinnedMobile: false, tooltip: 'designWork' },
  {
    id: 'youtube',
    labelKey: 'dockYoutube',
    icon: 'youtube',
    pinnedMobile: false,
    tooltip: 'videoProjects',
  },
  { id: 'safari', labelKey: 'dockSafari', icon: 'safari', pinnedMobile: false, tooltip: 'links' },
  {
    id: 'finder',
    labelKey: 'dockFinder',
    icon: 'finder',
    pinnedMobile: true,
    tooltip: 'allProjects',
  },
  {
    id: 'messages',
    labelKey: 'dockMessages',
    icon: 'messages',
    pinnedMobile: false,
    tooltip: 'messages',
    noWindow: true,
  },
  {
    id: 'terminal',
    labelKey: 'dockTerminal',
    icon: 'terminal',
    pinnedMobile: false,
    tooltip: 'terminal',
    noWindow: true,
  },
  {
    id: 'trash',
    labelKey: 'dockTrash',
    icon: 'trash',
    pinnedMobile: false,
    tooltip: 'trash',
    noWindow: true,
    separatorBefore: true,
  },
];
